version: '3.7'

services:
  node-server:
    extends:
      file: docker-compose.yml
      service: node-server
    environment:
      DATABASE_HOST: db
      DATABASE_SYSTEM: mariadb
    depends_on: 
      - db

  db:
    extends:
      file: docker-compose.yml
      service: db
    image: mariadb:10.7.1
    ports:
      - "3306:3306"
    volumes:
      - compare-databases-193_mariadb:/var/lib/mysql
    environment:
      MARIADB_USER: root
      MARIADB_ROOT_PASSWORD: password
      MARIADB_DATABASE: database
    restart: always

volumes:
   compare-databases-193_mariadb:
    name: compare-databases-193_mariadb
