version: '3.7'

services:
  node-server:
    extends:
      file: docker-compose.yml
      service: node-server
    environment:
      DATABASE_HOST: db
      DATABASE_SYSTEM: postgres

  node-client:
    extends:
      file: docker-compose.yml
      service: node-client

  db:
    extends:
      file: docker-compose.yml
      service: db
    image: postgres:14.1
    ports:
      - "5432:5432"
    volumes:
      - compare-databases-193_psql:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: password
      POSTGRES_DB: database
      POSTGRES_INITDB_ARGS: "--encoding=UTF-8"
    hostname: postgres
    restart: always

volumes:
   compare-databases-193_psql:
    name: compare-databases-193_psql
