version: '3.7'

services:
  node-server:
    extends:
      file: docker-compose.yml
      service: node-server
    image: compare-databases-193_node-server-sqlite
    build: 
      context: "./container/node-server-sqlite/"
    volumes:
      - compare-databases-193_sqlite:/home/db
    environment:
      DATABASE_HOST: /home/db/sqlite.db
      DATABASE_SYSTEM: sqlite

  node-client:
    extends:
      file: docker-compose.yml
      service: node-client

volumes:
   compare-databases-193_sqlite:
    name: compare-databases-193_sqlite
