version: '3.7'

services:
  node:
    extends:
      file: docker-compose.yml
      service: node
    image: sequelize-databases-performance_node-sqlite
    build: 
      context: "./container/"
      dockerfile: "Dockerfile.node-sqlite"
    volumes:
      - db-performance-sqlite:/home/db
    environment:
      NODE_ENV: sqlite

volumes:
  db-performance-sqlite:
