version: '3.7'

services:
  node-server:
    build: 
      context: "./container/node-server/"
    image: compare-databases-193_node-server
    container_name: compare-databases-193_node-server
    ports:
      - "8000:8000"
    volumes:
      - ./src/response-api:/home/response-api
      - ./logs:/home/logs/
    environment:
      NODE_PATH: "/home/response-api/"
      LOG_PATH: "/home/logs/"
      PATH: "${SDP_PATH}"
    user: "${SDP_UID}:${SDP_GID}"
    #restart: always
    tty: true

  node-client:
    build: 
      context: "./container/node-client/"
    image: compare-databases-193_node-client
    container_name: compare-databases-193_node-client
    ports:
      - "3000:3000"
    volumes:
      - ./src/request-page:/home/request-page
      - ./logs:/home/logs/
    environment:
      LOG_PATH: "/home/logs/"
    user: "${SDP_UID}:${SDP_GID}"
    restart: always
    tty: true

  db:
    container_name: compare-databases-193_db 
