version: '3.7'

services:
  node:
    build: 
      context: "./container/node/"
    image: sequelize-databases-performance_node
    container_name: sequelize-databases-performance_node 
    ports:
      - "3000:3000"
    volumes:
      - ./src:/home/app/
      - ./logs:/home/logs/
    environment:
      NODE_PATH: "/home/app/perfomance-api/"
      LOG_PATH: "/home/logs/"
      PATH: "${SDP_PATH}"
    user: "${SDP_UID}:${SDP_GID}"
    restart: always
    tty: true

  db:
    container_name: sequelize-databases-performance_db 
