version: '3.7'

services:
  node:
    extends:
      file: docker-compose.yml
      service: node
    environment:
      NODE_ENV: psql

  db:
    extends:
      file: docker-compose.yml
      service: db
    image: postgres:14.1
    ports:
      - "5432:5432"
    volumes:
      - db-performance-psql:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: password
      POSTGRES_DB: database
      POSTGRES_INITDB_ARGS: "--encoding=UTF-8"
    hostname: postgres
    restart: always

volumes:
  db-performance-psql:
