version: '3.7'

services:
  node-server:
    build: 
      context: "./container/node-server/"
    image: compare-databases-193_node-server
    container_name: compare-databases-193_node-server
    ports:
      - "8000:8000"
    volumes:
      - ./src/response-api:/home/response-api
      - ./logs:/home/logs/
    environment:
      NODE_PATH: "/home/response-api/"
      LOG_PATH: "/home/logs/${SDP_LOGPATH}/"
      PATH: "${SDP_PATH}"
    user: "${SDP_UID}:${SDP_GID}"
    tty: true

  db:
    container_name: compare-databases-193_db 
