version: '3.7'

services:
  node:
    build: 
      context: "./container/"
      dockerfile: "Dockerfile.node-sqlite"
    volumes:
      - db-performance-sqlite:/home/db
    environment:
      NODE_ENV: sqlite

volumes:
  db-performance-sqlite:
