version: '3.7'

services:
  node:
    extends:
      file: docker-compose.yml
      service: node
    image: sequelize-databases-performance_node-sqlite
    build: 
      context: "./container/node-sqlite/"
    volumes:
      - sequelize-databases-performance-sqlite:/home/db
    environment:
      DATABASE_HOST: /home/db/sqlite.db
      DATABASE_SYSTEM: sqlite

volumes:
  sequelize-databases-performance-sqlite:
    name: sequelize-databases-performance-sqlite
