version: '3.7'

services:
  node:
    container_name: sequelize-databases-performance_node 
    build: 
      context: "./container/"
      dockerfile: "Dockerfile.node"
    ports:
      - "3000:3000"
    volumes:
      - ./src:/home/app/
    environment:
      NODE_PATH: "/home/app/perfomance-api/"
    restart: always
    tty: true

  db:
    container_name: sequelize-databases-performance_db 
